# Project
version=1.0-SNAPSHOT
group=dev.cootshk
javaVersion=21
# Library metadata
modName=MixinKt
modAuthor=Cootshk
modId=mixinkt
license=GPLv3+
credits=
description=
# Libs
mixinVersion=0.8.7
mixinextrasVersion=0.5.4
asmVersion=9.9
floggerVersion=0.9
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true